import { ImageSourcePropType } from "react-native";
import {v1} from "uuid";

const Images = {
    AUTUMN_CIRCULATE: require("../assets/video_img/autumn/AUTUMN_CIRCULATE.png"),
    AUTUMN_COMPLETE: require("../assets/video_img/autumn/AUTUMN_COMPLETE.png"),
    AUTUMN_PURGE: require("../assets/video_img/autumn/AUTUMN_PURGE.png"),
    AUTUMN_TONIFY: require("../assets/video_img/autumn/AUTUMN_TONIFY.png"),
    EMBRACE_THE_TREE: require("../assets/video_img/autumn/EMBRACE_THE_TREE.png"),
    IMMUNE_SUPPORT: require("../assets/video_img/autumn/IMMUNE_SUPPORT.png"),
    EARTH_ELEMENT: require("../assets/video_img/later_summer/EARTH_ELEMENT.png"),
    HAPPY_SPLEEN_STOMACH: require("../assets/video_img/later_summer/HAPPY_SPLEEN_STOMACH.png"),
    LATE_SUMMER_CIRCULATE: require("../assets/video_img/later_summer/LATE_SUMMER_CIRCULATE.png"),
    LATE_SUMMER_PURGE: require("../assets/video_img/later_summer/LATE_SUMMER_PURGE.png"),
    LATE_SUMMER_TONIFY: require("../assets/video_img/later_summer/LATE_SUMMER_TONIFY.png"),
    THE_THREE_FORCES_STANDING_MEDITATION: require("../assets/video_img/later_summer/THE_THREE_FORCES_STANDING_MEDITATION.png"),
    ENERGY_SYSTEM_REBOOT: require("../assets/video_img/spring/ENERGY_SYSTEM_REBOOT.png"),
    HAPPY_LIVER: require("../assets/video_img/spring/HAPPY_LIVER.png"),
    HITTING_WITH_SOUNDS: require("../assets/video_img/spring/HITTING_WITH_SOUNDS.png"),
    SPRING_CIRCULATE: require("../assets/video_img/spring/SPRING_CIRCULATE.png"),
    SPRING_PURGE: require("../assets/video_img/spring/SPRING_PURGE.png"),
    SPRING_TONIFY: require("../assets/video_img/spring/SPRING_TONIFY.png"),
    FIFTY_MIN_SUMMER_TONIFY: require("../assets/video_img/summer/FIFTY_MIN_SUMMER_TONIFY.png"),
    HAPPY_HEART: require("../assets/video_img/summer/HAPPY_HEART.png"),
    SEATED_HAPPY_HEART: require("../assets/video_img/summer/SEATED_HAPPY_HEART.png"),
    SUMMER_CIRCULATE: require("../assets/video_img/summer/SUMMER_CIRCULATE.png"),
    SUMMER_PURGE: require("../assets/video_img/summer/SUMMER_PURGE.png"),
    SUMMER_TONIFY: require("../assets/video_img/summer/SUMMER_TONIFY.png"),
    INTRODUCTION_WINTER: require("../assets/video_img/winter/INTRODUCTION_WINTER.png"),
    SELF_MASSAGE_FOR_WINTER: require("../assets/video_img/winter/SELF_MASSAGE_FOR_WINTER.png"),
    WINTER_CIRCULATE: require("../assets/video_img/winter/WINTER_CIRCULATE.png"),
    WINTER_PURGE: require("../assets/video_img/winter/WINTER_PURGE.png"),
    WINTER_SOLSTICE: require("../assets/video_img/winter/WINTER_SOLSTICE.png"),
    WINTER_TONIFY: require("../assets/video_img/winter/WINTER_TONIFY.png"),
}

// import AUTUMN_CIRCULATE from "../assets/video_img/autumn/AUTUMN_CIRCULATE.png";
// import AUTUMN_COMPLETE from "../img/video_img/autumn/AUTUMN_COMPLETE.png";
// import AUTUMN_PURGE from "../img/video_img/autumn/AUTUMN_PURGE.png";
// import AUTUMN_TONIFY from "../img/video_img/autumn/AUTUMN_TONIFY.png";
// import EMBRACE_THE_TREE from "../img/video_img/autumn/EMBRACE_THE_TREE.png";
// import IMMUNE_SUPPORT from "../img/video_img/autumn/IMMUNE_SUPPORT.png";
// import EARTH_ELEMENT from "../img/video_img/later_summer/EARTH_ELEMENT.png";
// import HAPPY_SPLEEN_STOMACH from "../img/video_img/later_summer/HAPPY_SPLEEN_STOMACH.png";
// import LATE_SUMMER_CIRCULATE from "../img/video_img/later_summer/LATE_SUMMER_CIRCULATE.png";
// import LATE_SUMMER_PURGE from "../img/video_img/later_summer/LATE_SUMMER_PURGE.png";
// import LATE_SUMMER_TONIFY from "../img/video_img/later_summer/LATE_SUMMER_TONIFY.png";
// import THE_THREE_FORCES_STANDING_MEDITATION
//     from "../img/video_img/later_summer/THE_THREE_FORCES_STANDING_MEDITATION.png";
// import ENERGY_SYSTEM_REBOOT from "../img/video_img/spring/ENERGY_SYSTEM_REBOOT.png";
// import HAPPY_LIVER from "../img/video_img/spring/HAPPY_LIVER.png";
// import HITTING_WITH_SOUNDS from "../img/video_img/spring/HITTING_WITH_SOUNDS.png";
// import SPRING_CIRCULATE from "../img/video_img/spring/SPRING_CIRCULATE.png";
// import SPRING_PURGE from "../img/video_img/spring/SPRING_PURGE.png";
// import SPRING_TONIFY from "../img/video_img/spring/SPRING_TONIFY.png";
// import FIFTY_MIN_SUMMER_TONIFY from "../img/video_img/summer/FIFTY_MIN_SUMMER_TONIFY.png";
// import HAPPY_HEART from "../img/video_img/summer/HAPPY_HEART.png";
// import SEATED_HAPPY_HEART from "../img/video_img/summer/SEATED_HAPPY_HEART.png";
// import SUMMER_CIRCULATE from "../img/video_img/summer/SUMMER_CIRCULATE.png";
// import SUMMER_PURGE from "../img/video_img/summer/SUMMER_PURGE.png";
// import SUMMER_TONIFY from "../img/video_img/summer/SUMMER_TONIFY.png";
// import INTRODUCTION_WINTER from "../img/video_img/winter/INTRODUCTION_WINTER.png";
// import SELF_MASSAGE_FOR_WINTER from "../img/video_img/winter/SELF_MASSAGE_FOR_WINTER.png";
// import WINTER_CIRCULATE from "../img/video_img/winter/WINTER_CIRCULATE.png";
// import WINTER_PURGE from "../img/video_img/winter/WINTER_PURGE.png";
// import WINTER_SOLSTICE from "../img/video_img/winter/WINTER_SOLSTICE.png";
// import WINTER_TONIFY from "../img/video_img/winter/WINTER_TONIFY.png";

// types for kinds of video

export type PhaseType = 'attune' | 'purge' | 'tonify' | 'grow' | 'circulate' | 'integrate';

export type SeasonType = 'spring' | 'summer' | 'later summer' | 'autumn' | 'winter';

export type ElementType = 'earth' | 'metal' | 'water' | 'wood' | 'fire';

export type OrganType = 'body' | 'breath' | 'essence' | 'qi' | 'emotional mind' | 'spirit';

// type of video

export type VideoType = {
    id: string,
    photoPath: ImageSourcePropType,
    title: string,
    description: string,
    phase: PhaseType,
    season: SeasonType,
    element: ElementType,
    organ: OrganType
}

const fakeVideos: Array<VideoType> = [
    {
        id: v1(),
        title: 'AUTUMN CIRCULATE',
        photoPath: Images.AUTUMN_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'autumn',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'AUTUMN COMPLETE',
        photoPath: Images.AUTUMN_COMPLETE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'metal',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'AUTUMN PURGE',
        photoPath: Images.AUTUMN_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN TONIFY',
        photoPath: Images.AUTUMN_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'autumn',
        element: 'water',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'EMBRACE THE TREE',
        photoPath: Images.EMBRACE_THE_TREE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'autumn',
        element: 'wood',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'IMMUNE SUPPORT',
        photoPath: Images.IMMUNE_SUPPORT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'EARTH ELEMENT',
        photoPath: Images.EARTH_ELEMENT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'fire',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'HAPPY SPLEEN STOMACH',
        photoPath: Images.HAPPY_SPLEEN_STOMACH,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER CIRCULATE',
        photoPath: Images.LATE_SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'later summer',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'LATE SUMMER PURGE',
        photoPath: Images.LATE_SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'later summer',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER TONIFY',
        photoPath: Images.LATE_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'later summer',
        element: 'water',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'THE THREE FORCES STANDING MEDITATION',
        photoPath: Images.THE_THREE_FORCES_STANDING_MEDITATION,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'ENERGY SYSTEM REBOOT',
        photoPath: Images.ENERGY_SYSTEM_REBOOT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'spring',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'HAPPY LIVER',
        photoPath: Images.HAPPY_LIVER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'spring',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'HITTING WITH SOUNDS',
        photoPath: Images.HITTING_WITH_SOUNDS,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SPRING CIRCULATE',
        photoPath: Images.SPRING_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'spring',
        element: 'wood',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SPRING PURGE',
        photoPath: Images.SPRING_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'wood',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SPRING TONIFY',
        photoPath: Images.SPRING_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'spring',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'FIFTY MIN SUMMER TONIFY',
        photoPath: Images.FIFTY_MIN_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'HAPPY HEART',
        photoPath: Images.HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'SEATED HAPPY HEART',
        photoPath: Images.SEATED_HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SUMMER CIRCULATE',
        photoPath: Images.SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'SUMMER PURGE',
        photoPath: Images.SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'summer',
        element: 'earth',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SUMMER TONIFY',
        photoPath: Images.SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'INTRODUCTION WINTER',
        photoPath: Images.INTRODUCTION_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SELF MASSAGE FOR WINTER',
        photoPath: Images.SELF_MASSAGE_FOR_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'WINTER CIRCULATE',
        photoPath: Images.WINTER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'winter',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'WINTER PURGE',
        photoPath: Images.WINTER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'winter',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'WINTER SOLSTICE',
        photoPath: Images.WINTER_SOLSTICE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'grow',
        season: 'winter',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'WINTER TONIFY',
        photoPath: Images.WINTER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'winter',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN CIRCULATE',
        photoPath: Images.AUTUMN_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'autumn',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'AUTUMN COMPLETE',
        photoPath: Images.AUTUMN_COMPLETE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'metal',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'AUTUMN PURGE',
        photoPath: Images.AUTUMN_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN TONIFY',
        photoPath: Images.AUTUMN_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'autumn',
        element: 'water',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'EMBRACE THE TREE',
        photoPath: Images.EMBRACE_THE_TREE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'autumn',
        element: 'wood',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'IMMUNE SUPPORT',
        photoPath: Images.IMMUNE_SUPPORT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'EARTH ELEMENT',
        photoPath: Images.EARTH_ELEMENT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'fire',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'HAPPY SPLEEN STOMACH',
        photoPath: Images.HAPPY_SPLEEN_STOMACH,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER CIRCULATE',
        photoPath: Images.LATE_SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'later summer',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'LATE SUMMER PURGE',
        photoPath: Images.LATE_SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'later summer',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER TONIFY',
        photoPath: Images.LATE_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'later summer',
        element: 'water',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'THE THREE FORCES STANDING MEDITATION',
        photoPath: Images.THE_THREE_FORCES_STANDING_MEDITATION,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'ENERGY SYSTEM REBOOT',
        photoPath: Images.ENERGY_SYSTEM_REBOOT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'spring',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'HAPPY LIVER',
        photoPath: Images.HAPPY_LIVER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'spring',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'HITTING WITH SOUNDS',
        photoPath: Images.HITTING_WITH_SOUNDS,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SPRING CIRCULATE',
        photoPath: Images.SPRING_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'spring',
        element: 'wood',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SPRING PURGE',
        photoPath: Images.SPRING_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'wood',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SPRING TONIFY',
        photoPath: Images.SPRING_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'spring',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'FIFTY MIN SUMMER TONIFY',
        photoPath: Images.FIFTY_MIN_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'HAPPY HEART',
        photoPath: Images.HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'SEATED HAPPY HEART',
        photoPath: Images.SEATED_HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SUMMER CIRCULATE',
        photoPath: Images.SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'SUMMER PURGE',
        photoPath: Images.SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'summer',
        element: 'earth',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SUMMER TONIFY',
        photoPath: Images.SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'INTRODUCTION WINTER',
        photoPath: Images.INTRODUCTION_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SELF MASSAGE FOR WINTER',
        photoPath: Images.SELF_MASSAGE_FOR_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'WINTER CIRCULATE',
        photoPath: Images.WINTER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'winter',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'WINTER PURGE',
        photoPath: Images.WINTER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'winter',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'WINTER SOLSTICE',
        photoPath: Images.WINTER_SOLSTICE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'grow',
        season: 'winter',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'WINTER TONIFY',
        photoPath: Images.WINTER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'winter',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN CIRCULATE',
        photoPath: Images.AUTUMN_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'autumn',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'AUTUMN COMPLETE',
        photoPath: Images.AUTUMN_COMPLETE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'metal',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'AUTUMN PURGE',
        photoPath: Images.AUTUMN_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN TONIFY',
        photoPath: Images.AUTUMN_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'autumn',
        element: 'water',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'EMBRACE THE TREE',
        photoPath: Images.EMBRACE_THE_TREE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'autumn',
        element: 'wood',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'IMMUNE SUPPORT',
        photoPath: Images.IMMUNE_SUPPORT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'EARTH ELEMENT',
        photoPath: Images.EARTH_ELEMENT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'fire',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'HAPPY SPLEEN STOMACH',
        photoPath: Images.HAPPY_SPLEEN_STOMACH,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER CIRCULATE',
        photoPath: Images.LATE_SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'later summer',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'LATE SUMMER PURGE',
        photoPath: Images.LATE_SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'later summer',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER TONIFY',
        photoPath: Images.LATE_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'later summer',
        element: 'water',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'THE THREE FORCES STANDING MEDITATION',
        photoPath: Images.THE_THREE_FORCES_STANDING_MEDITATION,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'ENERGY SYSTEM REBOOT',
        photoPath: Images.ENERGY_SYSTEM_REBOOT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'spring',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'HAPPY LIVER',
        photoPath: Images.HAPPY_LIVER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'spring',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'HITTING WITH SOUNDS',
        photoPath: Images.HITTING_WITH_SOUNDS,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SPRING CIRCULATE',
        photoPath: Images.SPRING_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'spring',
        element: 'wood',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SPRING PURGE',
        photoPath: Images.SPRING_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'wood',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SPRING TONIFY',
        photoPath: Images.SPRING_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'spring',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'FIFTY MIN SUMMER TONIFY',
        photoPath: Images.FIFTY_MIN_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'HAPPY HEART',
        photoPath: Images.HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'SEATED HAPPY HEART',
        photoPath: Images.SEATED_HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SUMMER CIRCULATE',
        photoPath: Images.SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'SUMMER PURGE',
        photoPath: Images.SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'summer',
        element: 'earth',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SUMMER TONIFY',
        photoPath: Images.SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'INTRODUCTION WINTER',
        photoPath: Images.INTRODUCTION_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SELF MASSAGE FOR WINTER',
        photoPath: Images.SELF_MASSAGE_FOR_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'WINTER CIRCULATE',
        photoPath: Images.WINTER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'winter',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'WINTER PURGE',
        photoPath: Images.WINTER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'winter',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'WINTER SOLSTICE',
        photoPath: Images.WINTER_SOLSTICE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'grow',
        season: 'winter',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'WINTER TONIFY',
        photoPath: Images.WINTER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'winter',
        element: 'water',
        organ: 'breath',
    },
];

export type SetVideosActionType = {
    type: 'SET-VIDEOS',
    videos: Array<VideoType>,
}

type ActionsType = SetVideosActionType ;


export const videoListReducer = (state: Array<VideoType> = fakeVideos, action: ActionsType): Array<VideoType> => {
    switch (action.type) {
        case 'SET-VIDEOS': {
            return JSON.parse(JSON.stringify(action.videos));
        }

        default:
            return state;
    }
}

export const setVideosAC = (videos: Array<VideoType>): SetVideosActionType => {
    return {type: 'SET-VIDEOS', videos}
}

