import {v1} from "uuid";
const AUTUMN_CIRCULATE = "../assets/video_img/autumn/AUTUMN_CIRCULATE.png";
const AUTUMN_COMPLETE = "../assets/video_img/autumn/AUTUMN_COMPLETE.png";
const AUTUMN_PURGE = "../assets/video_img/autumn/AUTUMN_PURGE.png";
const AUTUMN_TONIFY = "../assets/video_img/autumn/AUTUMN_TONIFY.png";
const EMBRACE_THE_TREE = "../assets/video_img/autumn/EMBRACE_THE_TREE.png";
const IMMUNE_SUPPORT = "../assets/video_img/autumn/IMMUNE_SUPPORT.png";
const EARTH_ELEMENT = "../assets/video_img/later_summer/EARTH_ELEMENT.png";
const HAPPY_SPLEEN_STOMACH = "../assets/video_img/later_summer/HAPPY_SPLEEN_STOMACH.png";
const LATE_SUMMER_CIRCULATE = "../assets/video_img/later_summer/LATE_SUMMER_CIRCULATE.png";
const LATE_SUMMER_PURGE = "../assets/video_img/later_summer/LATE_SUMMER_PURGE.png";
const LATE_SUMMER_TONIFY = "../assets/video_img/later_summer/LATE_SUMMER_TONIFY.png";
const THE_THREE_FORCES_STANDING_MEDITATION = "../assets/video_img/later_summer/THE_THREE_FORCES_STANDING_MEDITATION.png";
const ENERGY_SYSTEM_REBOOT = "../assets/video_img/spring/ENERGY_SYSTEM_REBOOT.png";
const HAPPY_LIVER = "../assets/video_img/spring/HAPPY_LIVER.png";
const HITTING_WITH_SOUNDS = "../assets/video_img/spring/HITTING_WITH_SOUNDS.png";
const SPRING_CIRCULATE = "../assets/video_img/spring/SPRING_CIRCULATE.png";
const SPRING_PURGE = "../assets/video_img/spring/SPRING_PURGE.png";
const SPRING_TONIFY = "../assets/video_img/spring/SPRING_TONIFY.png";
const FIFTY_MIN_SUMMER_TONIFY = "../assets/video_img/summer/FIFTY_MIN_SUMMER_TONIFY.png";
const HAPPY_HEART = "../assets/video_img/summer/HAPPY_HEART.png";
const SEATED_HAPPY_HEART = "../assets/video_img/summer/SEATED_HAPPY_HEART.png";
const SUMMER_CIRCULATE = "../assets/video_img/summer/SUMMER_CIRCULATE.png";
const SUMMER_PURGE = "../assets/video_img/summer/SUMMER_PURGE.png";
const SUMMER_TONIFY = "../assets/video_img/summer/SUMMER_TONIFY.png";
const INTRODUCTION_WINTER = "../assets/video_img/winter/INTRODUCTION_WINTER.png";
const SELF_MASSAGE_FOR_WINTER = "../assets/video_img/winter/SELF_MASSAGE_FOR_WINTER.png";
const WINTER_CIRCULATE = "../assets/video_img/winter/WINTER_CIRCULATE.png";
const WINTER_PURGE = "../assets/video_img/winter/WINTER_PURGE.png";
const WINTER_SOLSTICE = "../assets/video_img/winter/WINTER_SOLSTICE.png";
const WINTER_TONIFY = "../assets/video_img/winter/WINTER_TONIFY.png";

// types for kinds of video

export type PhaseType = 'attune' | 'purge' | 'tonify' | 'grow' | 'circulate' | 'integrate';

export type SeasonType = 'spring' | 'summer' | 'later summer' | 'autumn' | 'winter';

export type ElementType = 'earth' | 'metal' | 'water' | 'wood' | 'fire';

export type OrganType = 'body' | 'breath' | 'essence' | 'qi' | 'emotional mind' | 'spirit';

// type of video

export type VideoType = {
    id: string,
    photoPath: string,
    title: string,
    description: string,
    phase: PhaseType,
    season: SeasonType,
    element: ElementType,
    organ: OrganType
}

const fakeVideos: Array<VideoType> = [
    {
        id: v1(),
        title: 'AUTUMN CIRCULATE',
        photoPath: AUTUMN_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'autumn',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'AUTUMN COMPLETE',
        photoPath: AUTUMN_COMPLETE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'metal',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'AUTUMN PURGE',
        photoPath: AUTUMN_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN TONIFY',
        photoPath: AUTUMN_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'autumn',
        element: 'water',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'EMBRACE THE TREE',
        photoPath: EMBRACE_THE_TREE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'autumn',
        element: 'wood',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'IMMUNE SUPPORT',
        photoPath: IMMUNE_SUPPORT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'EARTH ELEMENT',
        photoPath: EARTH_ELEMENT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'fire',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'HAPPY SPLEEN STOMACH',
        photoPath: HAPPY_SPLEEN_STOMACH,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER CIRCULATE',
        photoPath: LATE_SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'later summer',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'LATE SUMMER PURGE',
        photoPath: LATE_SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'later summer',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER TONIFY',
        photoPath: LATE_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'later summer',
        element: 'water',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'THE THREE FORCES STANDING MEDITATION',
        photoPath: THE_THREE_FORCES_STANDING_MEDITATION,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'ENERGY SYSTEM REBOOT',
        photoPath: ENERGY_SYSTEM_REBOOT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'spring',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'HAPPY LIVER',
        photoPath: HAPPY_LIVER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'spring',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'HITTING WITH SOUNDS',
        photoPath: HITTING_WITH_SOUNDS,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SPRING CIRCULATE',
        photoPath: SPRING_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'spring',
        element: 'wood',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SPRING PURGE',
        photoPath: SPRING_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'wood',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SPRING TONIFY',
        photoPath: SPRING_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'spring',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'FIFTY MIN SUMMER TONIFY',
        photoPath: FIFTY_MIN_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'HAPPY HEART',
        photoPath: HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'SEATED HAPPY HEART',
        photoPath: SEATED_HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SUMMER CIRCULATE',
        photoPath: SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'SUMMER PURGE',
        photoPath: SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'summer',
        element: 'earth',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SUMMER TONIFY',
        photoPath: SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'INTRODUCTION WINTER',
        photoPath: INTRODUCTION_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SELF MASSAGE FOR WINTER',
        photoPath: SELF_MASSAGE_FOR_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'WINTER CIRCULATE',
        photoPath: WINTER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'winter',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'WINTER PURGE',
        photoPath: WINTER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'winter',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'WINTER SOLSTICE',
        photoPath: WINTER_SOLSTICE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'grow',
        season: 'winter',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'WINTER TONIFY',
        photoPath: WINTER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'winter',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN CIRCULATE',
        photoPath: AUTUMN_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'autumn',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'AUTUMN COMPLETE',
        photoPath: AUTUMN_COMPLETE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'metal',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'AUTUMN PURGE',
        photoPath: AUTUMN_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN TONIFY',
        photoPath: AUTUMN_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'autumn',
        element: 'water',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'EMBRACE THE TREE',
        photoPath: EMBRACE_THE_TREE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'autumn',
        element: 'wood',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'IMMUNE SUPPORT',
        photoPath: IMMUNE_SUPPORT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'EARTH ELEMENT',
        photoPath: EARTH_ELEMENT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'fire',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'HAPPY SPLEEN STOMACH',
        photoPath: HAPPY_SPLEEN_STOMACH,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER CIRCULATE',
        photoPath: LATE_SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'later summer',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'LATE SUMMER PURGE',
        photoPath: LATE_SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'later summer',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER TONIFY',
        photoPath: LATE_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'later summer',
        element: 'water',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'THE THREE FORCES STANDING MEDITATION',
        photoPath: THE_THREE_FORCES_STANDING_MEDITATION,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'ENERGY SYSTEM REBOOT',
        photoPath: ENERGY_SYSTEM_REBOOT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'spring',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'HAPPY LIVER',
        photoPath: HAPPY_LIVER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'spring',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'HITTING WITH SOUNDS',
        photoPath: HITTING_WITH_SOUNDS,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SPRING CIRCULATE',
        photoPath: SPRING_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'spring',
        element: 'wood',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SPRING PURGE',
        photoPath: SPRING_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'wood',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SPRING TONIFY',
        photoPath: SPRING_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'spring',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'FIFTY MIN SUMMER TONIFY',
        photoPath: FIFTY_MIN_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'HAPPY HEART',
        photoPath: HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'SEATED HAPPY HEART',
        photoPath: SEATED_HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SUMMER CIRCULATE',
        photoPath: SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'SUMMER PURGE',
        photoPath: SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'summer',
        element: 'earth',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SUMMER TONIFY',
        photoPath: SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'INTRODUCTION WINTER',
        photoPath: INTRODUCTION_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SELF MASSAGE FOR WINTER',
        photoPath: SELF_MASSAGE_FOR_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'WINTER CIRCULATE',
        photoPath: WINTER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'winter',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'WINTER PURGE',
        photoPath: WINTER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'winter',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'WINTER SOLSTICE',
        photoPath: WINTER_SOLSTICE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'grow',
        season: 'winter',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'WINTER TONIFY',
        photoPath: WINTER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'winter',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN CIRCULATE',
        photoPath: AUTUMN_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'autumn',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'AUTUMN COMPLETE',
        photoPath: AUTUMN_COMPLETE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'metal',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'AUTUMN PURGE',
        photoPath: AUTUMN_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'AUTUMN TONIFY',
        photoPath: AUTUMN_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'autumn',
        element: 'water',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'EMBRACE THE TREE',
        photoPath: EMBRACE_THE_TREE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'autumn',
        element: 'wood',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'IMMUNE SUPPORT',
        photoPath: IMMUNE_SUPPORT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'autumn',
        element: 'wood',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'EARTH ELEMENT',
        photoPath: EARTH_ELEMENT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'fire',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'HAPPY SPLEEN STOMACH',
        photoPath: HAPPY_SPLEEN_STOMACH,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER CIRCULATE',
        photoPath: LATE_SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'later summer',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'LATE SUMMER PURGE',
        photoPath: LATE_SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'later summer',
        element: 'fire',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'LATE SUMMER TONIFY',
        photoPath: LATE_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'later summer',
        element: 'water',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'THE THREE FORCES STANDING MEDITATION',
        photoPath: THE_THREE_FORCES_STANDING_MEDITATION,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'later summer',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'ENERGY SYSTEM REBOOT',
        photoPath: ENERGY_SYSTEM_REBOOT,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'attune',
        season: 'spring',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'HAPPY LIVER',
        photoPath: HAPPY_LIVER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'spring',
        element: 'water',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'HITTING WITH SOUNDS',
        photoPath: HITTING_WITH_SOUNDS,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SPRING CIRCULATE',
        photoPath: SPRING_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'spring',
        element: 'wood',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SPRING PURGE',
        photoPath: SPRING_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'spring',
        element: 'wood',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SPRING TONIFY',
        photoPath: SPRING_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'spring',
        element: 'water',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'FIFTY MIN SUMMER TONIFY',
        photoPath: FIFTY_MIN_SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'HAPPY HEART',
        photoPath: HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'SEATED HAPPY HEART',
        photoPath: SEATED_HAPPY_HEART,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'SUMMER CIRCULATE',
        photoPath: SUMMER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'summer',
        element: 'earth',
        organ: 'spirit',
    },
    {
        id: v1(),
        title: 'SUMMER PURGE',
        photoPath: SUMMER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'summer',
        element: 'earth',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'SUMMER TONIFY',
        photoPath: SUMMER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'summer',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'INTRODUCTION WINTER',
        photoPath: INTRODUCTION_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'body',
    },
    {
        id: v1(),
        title: 'SELF MASSAGE FOR WINTER',
        photoPath: SELF_MASSAGE_FOR_WINTER,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'integrate',
        season: 'winter',
        element: 'earth',
        organ: 'breath',
    },
    {
        id: v1(),
        title: 'WINTER CIRCULATE',
        photoPath: WINTER_CIRCULATE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'circulate',
        season: 'winter',
        element: 'fire',
        organ: 'essence',
    },
    {
        id: v1(),
        title: 'WINTER PURGE',
        photoPath: WINTER_PURGE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'purge',
        season: 'winter',
        element: 'wood',
        organ: 'qi',
    },
    {
        id: v1(),
        title: 'WINTER SOLSTICE',
        photoPath: WINTER_SOLSTICE,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'grow',
        season: 'winter',
        element: 'metal',
        organ: 'emotional mind',
    },
    {
        id: v1(),
        title: 'WINTER TONIFY',
        photoPath: WINTER_TONIFY,
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        phase: 'tonify',
        season: 'winter',
        element: 'water',
        organ: 'breath',
    },
];

export type SetVideosActionType = {
    type: 'SET-VIDEOS',
    videos: Array<VideoType>,
}

type ActionsType = SetVideosActionType ;


export const videoListReducer = (state: Array<VideoType> = fakeVideos, action: ActionsType): Array<VideoType> => {
    switch (action.type) {
        case 'SET-VIDEOS': {
            return JSON.parse(JSON.stringify(action.videos));
        }

        default:
            return state;
    }
}

export const setVideosAC = (videos: Array<VideoType>): SetVideosActionType => {
    return {type: 'SET-VIDEOS', videos}
}

